### ISSUE TITLE
Cant run, from Prices import price_grabber as pg 

### ISSUE THREAD

**Issue by jbb1999** [TomDra/CSGO-Case-Data-Analysis#1]
It wont run because of this and it seems that it is not defined in the version i have. Can you check the most recent upload and see if im doing something wrong or if you forgot to update the price_grabber.py?

**Comment by TomDra** [comment]
Did you make sure to install all the required files? try downloading the latest release and use python 3.9

**Comment by TomDra** [comment]
Actually, I just noticed that an error is now thrown due to the new skin (Kiss♥Love), I am going to try and sort it tonight or tomorrow morning.

**Comment by jbb1999** [comment]
Ok!

**Comment by jbb1999** [comment]
I had my env setup wrong, and it seems to work better. 
FAMAS-Meow-36 could not convert string to float: 'kr 3775'
Traceback (most recent call last):
  File "D:\Projects\bots\CSGO\CSGO case profit\main.py", line 61, in <module>
    pg.item_case_search(files)
  File "D:\Projects\bots\CSGO\CSGO case profit\Prices\price_grabber.py", line 215, in item_case_search
    skin_prices(stash_ids, case_file, price_file)
  File "D:\Projects\bots\CSGO\CSGO case profit\Prices\price_grabber.py", line 181, in skin_prices
    price = csgostash_price(ids,skin)
  File "D:\Projects\bots\CSGO\CSGO case profit\Prices\price_grabber.py", line 158, in csgostash_price
    return avg_prices
UnboundLocalError: local variable 'avg_prices' referenced before assignment

Process finished with exit code 1
turns out not, just as it ends i get this

**Comment by TomDra** [comment]
I have updated the code and it should no longer error and run perfectly.
Please message back if not.

Thanks

**Comment by jbb1999** [comment]
FIxed!
